#include <algorithm>
#include <cstddef>
#include <print>
#include <string>
#include <string_view>
#include <vector>

#include <gnuradio-4.0/Block.hpp>
#include <gnuradio-4.0/BlockRegistry.hpp>
#include <gnuradio-4.0/config.hpp>

#include <minimal_blocklib/Gain.hpp>
#include <other_blocklib/Gain.hpp>

#include <gnuradio-4.0/MinimalBlockLib.hpp> // generated by gr_add_block_library
#include <gnuradio-4.0/OtherBlockLib.hpp>   // generated by gr_add_block_library

// Two block libraries whose registering headers share a basename, linked into one program. The
// generated factory, registration and initializer symbols are derived from that basename, so they
// are qualified by the module name as well; without that qualification the two libraries define the
// same symbols and each library's initializer reaches whichever definition the link resolved first,
// which registers one library's blocks under both initializers.
namespace {
[[nodiscard]] bool holds(const gr::BlockRegistry& registry, std::string_view qualifier) {
    const std::vector<std::string> keys = registry.keys();
    return std::ranges::any_of(keys, [qualifier](const std::string& key) { return key.contains(qualifier); });
}
} // namespace

int main() {
    gr::minimal_blocklib::Gain<float> fromMinimal;
    gr::other_blocklib::Gain<float>   fromOther;
    fromMinimal.gain = 2.0F;
    fromOther.gain   = 3.0F;
    if (fromMinimal.processOne(3.0F) != 6.0F || fromOther.processOne(3.0F) != 9.0F) {
        std::println(stderr, "a directly instantiated block did not compute");
        return 1;
    }

    gr::BlockRegistry minimal;
    gr::BlockRegistry other;
    const std::size_t nMinimal = gr::blocklib::initMinimalBlockLib(minimal);
    const std::size_t nOther   = gr::blocklib::initOtherBlockLib(other);

#ifdef GR_ENABLE_BLOCK_REGISTRY
    if (nMinimal == 0UZ || nOther == 0UZ) {
        std::println(stderr, "the initializers entered {} and {} blocks into their empty registries", nMinimal, nOther);
        return 2;
    }
    if (!holds(minimal, "minimal_blocklib") || holds(minimal, "other_blocklib")) {
        std::println(stderr, "MinimalBlockLib's initializer filled a registry of {} entries holding gr::other_blocklib: {}", minimal.keys().size(), holds(minimal, "other_blocklib"));
        return 3;
    }
    if (!holds(other, "other_blocklib") || holds(other, "minimal_blocklib")) {
        std::println(stderr, "OtherBlockLib's initializer filled a registry of {} entries holding gr::minimal_blocklib: {}", other.keys().size(), holds(other, "minimal_blocklib"));
        return 4;
    }
    std::println("each initializer registered its own library: {} and {} entries under their own namespaces", minimal.keys().size(), other.keys().size());
#else
    if (nMinimal != 0UZ || nOther != 0UZ) {
        std::println(stderr, "with the registry off the initializers entered {} and {} blocks", nMinimal, nOther);
        return 5;
    }
    std::println("registry off: both libraries compute by type and neither initializer registered a block");
#endif
    return 0;
}
