#include <algorithm>
#include <cstddef>
#include <print>
#include <string>
#include <vector>

#include <gnuradio-4.0/Block.hpp>
#include <gnuradio-4.0/BlockRegistry.hpp>
#include <gnuradio-4.0/config.hpp>
#include <minimal_blocklib/Gain.hpp>

#include <gnuradio-4.0/MinimalBlockLib.hpp> // generated by gr_add_block_library

// Explicit initialization is the contract for a linked block library, static or shared. A shared
// library that nothing references is not recorded in DT_NEEDED under the linker's default
// --as-needed, so it is never loaded and its static initializers never run; registration that
// relies on them is not portable. Calling the generated initializer registers the blocks, and it
// also keeps a static library's objects from being discarded.
int main() {
    gr::minimal_blocklib::Gain<float> direct;
    direct.gain = 2.0F;
    if (direct.processOne(3.0F) != 6.0F) {
        std::println(stderr, "the directly instantiated block did not compute");
        return 1;
    }

    // The initializer returns the number of blocks it newly registered, and registering a block the
    // registry already holds is a no-op rather than a failure. A fresh registry therefore reports
    // what the library added, and repeating the call reports nothing more.
    gr::BlockRegistry own;
    const std::size_t nAdded = gr::blocklib::initMinimalBlockLib(own);

#ifdef GR_ENABLE_BLOCK_REGISTRY
    if (nAdded == 0UZ) {
        std::println(stderr, "the initializer registered no block into an empty registry");
        return 5;
    }
    if (const std::size_t nAddedAgain = gr::blocklib::initMinimalBlockLib(own); nAddedAgain != 0UZ) {
        std::println(stderr, "re-initialization registered {} block(s) that were already present", nAddedAgain);
        return 6;
    }

    // The definition units also register into globalBlockRegistry() from a static initializer, so
    // this call meets blocks that are already there and adds nothing. What it has to establish is
    // the contract that matters for a linked block library: after initialization the registry finds
    // the block and constructs it.
    gr::BlockRegistry& registry   = gr::globalBlockRegistry();
    const std::size_t  initResult = gr::blocklib::initMinimalBlockLib(registry);

    const std::vector<std::string> keys = registry.keys();
    const auto                     gain = std::ranges::find_if(keys, [](const std::string& key) { return key.contains("Gain"); });
    if (gain == keys.end()) {
        std::println(stderr, "the registry has {} entries and none of them is the Gain block", keys.size());
        return 3;
    }

    const std::unique_ptr<gr::BlockModel> block = registry.create(*gain, {});
    if (!block) {
        std::println(stderr, "the registry knows '{}' but could not construct it", *gain);
        return 4;
    }

    std::println("constructed '{}' through the registry after explicit initialization (init added {} of {} entries)", *gain, initResult, own.keys().size());
#else
    // With the registry off the installed core keeps no factories, so the library's runtime face is
    // gone by construction: the block is still linked and still computes when its type is named,
    // and the initializer says what it did by entering nothing. The lookups the other branch makes
    // would all be answered by an empty registry, so none of them is asserted here.
    if (nAdded != 0UZ) {
        std::println(stderr, "with the registry off the initializer entered {} block(s)", nAdded);
        return 2;
    }
    std::println("registry off: the block computes when its type is named and the initializer entered no block");
#endif
    return 0;
}
