#include <algorithm>
#include <cstddef>
#include <print>
#include <string>
#include <string_view>
#include <vector>

#include <gnuradio-4.0/Block.hpp>
#include <gnuradio-4.0/BlockRegistry.hpp>
#include <gnuradio-4.0/config.hpp>

#include <named_registry_blocklib/Registry.hpp>
#include <named_registry_blocklib/Scale.hpp>

#include <gnuradio-4.0/NamedRegistryBlockLib.hpp> // generated by gr_add_block_library

// A block library built with REGISTRY_HEADER and REGISTRY_INSTANCE: its generated units insert into
// the registry this project declares, not into gr::globalBlockRegistry. The two options reach the
// generator only if gr_add_block_library() forwards them, and a library that drops them registers
// into the global registry instead, which is what the second assertion below catches.
namespace {
[[nodiscard]] bool holds(const gr::BlockRegistry& registry, std::string_view qualifier) {
    const std::vector<std::string> keys = registry.keys();
    return std::ranges::any_of(keys, [qualifier](const std::string& key) { return key.contains(qualifier); });
}
} // namespace

int main() {
    gr::named_registry_blocklib::Scale<float> direct;
    direct.factor = 4.0F;
    if (direct.processOne(3.0F) != 12.0F) {
        std::println(stderr, "the directly instantiated block did not compute");
        return 1;
    }

    const std::size_t nAdded = gr::blocklib::initNamedRegistryBlockLib(namedBlockRegistry());

#ifdef GR_ENABLE_BLOCK_REGISTRY
    if (!holds(namedBlockRegistry(), "named_registry_blocklib")) {
        std::println(stderr, "the named registry holds {} entries and none of them is the Scale block", namedBlockRegistry().keys().size());
        return 2;
    }
    if (holds(gr::globalBlockRegistry(), "named_registry_blocklib")) {
        std::println(stderr, "the library registered into gr::globalBlockRegistry() rather than into the registry it names");
        return 3;
    }
    std::println("the named registry holds {} entries and the global registry holds none of them (init added {})", namedBlockRegistry().keys().size(), nAdded);
#else
    if (nAdded != 0UZ || !namedBlockRegistry().keys().empty()) {
        std::println(stderr, "with the registry off the initializer entered {} block(s) into a registry of {} entries", nAdded, namedBlockRegistry().keys().size());
        return 4;
    }
    std::println("registry off: the block computes when its type is named and the named registry stayed empty");
#endif
    return 0;
}
